export const credits = [
  {
    modelName: 'Scifi terminal',
    modelLink: 'https://skfb.ly/orY6y',
    author: 'lorib2306',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'SciFi Desk',
    modelLink: 'https://skfb.ly/orY6yee',
    author: 'Sousinho',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Chopper’s Night - Cyberpunk Nightclub',
    modelLink: 'https://skfb.ly/oxxNt',
    author: 'lorib2306',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Sci-Fi Recon Drone',
    modelLink: 'https://skfb.ly/6VqqN',
    author: 'Matthew-David',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Sci-Fi Servers',
    modelLink: 'https://skfb.ly/oFSGV',
    author: 'Michael V',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Gaming Table',
    modelLink: 'https://skfb.ly/osOx8',
    author: 'chayaruart',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'SciFi Walkways Grunge Gate Closed',
    modelLink: 'https://skfb.ly/6XooY',
    author: 'Elliseran Modeller',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Futuristic cable car',
    modelLink: 'https://skfb.ly/oxExy',
    author: 'Nazareno_rojas',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
  {
    modelName: 'Sci- Fi Railing',
    modelLink: 'https://skfb.ly/oA8SC',
    author: '𝗻𝗲𝗻𝗸𝗲𝗮',
    licenseLink: 'https://creativecommons.org/licenses/by/4.0/',
    licenseName: 'Creative Commons Attribution',
  },
];
